version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: debate-ui/docker/Dockerfile
    image: debate-for-ai-alignment-ui
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1